services:
    tas2580.socialbuttons.listener:
        class: tas2580\socialbuttons\event\listener
        arguments:
            - @config
            - @template
            - @user
            - @request
            - %core.root_path%
        tags:
            - { name: event.listener }
            