services:
    tas2580.socialbuttons.listener:
        class: tas2580\socialbuttons\event\listener
        arguments:
            - @config
            - @template
        tags:
            - { name: event.listener }
